package penjualanbusanamuslim;
 
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class Frame_penjualan_busana_muslim extends javax.swing.JFrame {
    int harga, jumlahBeli, cash;
    double diskon, Subtotal, totalBayar, bayar, cash1, sisa;
    String sisa1;
 
    /**
     * Creates new form Frame_penjualan_busana_muslim
     */
    public Frame_penjualan_busana_muslim() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
 
        jNamaPogram = new javax.swing.JLabel();
        jPilihan = new javax.swing.JLabel();
        Pilihan1 = new javax.swing.JRadioButton();
        Pilihan2 = new javax.swing.JRadioButton();
        Pilihan3 = new javax.swing.JRadioButton();
        Pilihan4 = new javax.swing.JRadioButton();
        Pilihan5 = new javax.swing.JRadioButton();
        Pilihan6 = new javax.swing.JRadioButton();
        Pilihan7 = new javax.swing.JRadioButton();
        Pilihan8 = new javax.swing.JRadioButton();
        Pilihan9 = new javax.swing.JRadioButton();
        Pilihan10 = new javax.swing.JRadioButton();
        Pilihan11 = new javax.swing.JRadioButton();
        Pilihan12 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtSatuan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtDiskon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel_tempat_gambar = new javax.swing.JEditorPane();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        txtCash = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSisa = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();
        jProgressBar4 = new javax.swing.JProgressBar();
        btnExit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jProgressBar5 = new javax.swing.JProgressBar();
 
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
 
        jNamaPogram.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jNamaPogram.setForeground(new java.awt.Color(153, 0, 153));
        jNamaPogram.setText("Program Penjualan Busana Muslim Family");
 
        jPilihan.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jPilihan.setText("Pilihan Busana Muslim :");
 
        Pilihan1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Pilihan1.setText("Blue Saphire");
        Pilihan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihan1ActionPerformed(evt);
            }
        });
 
        Pilihan2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Pilihan2.setText("Blue Cool");
        Pilihan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihan2ActionPerformed(evt);
            }
        });
 
        Pilihan3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Pilihan3.setText("Brown Choco");
        Pilihan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihan3ActionPerformed(evt);
            }
        });
 
        Pilihan4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Pilihan4.setText("Choco Black");
        Pilihan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihan4ActionPerformed(evt);
            }
        });
 
        Pilihan5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Pilihan5.setText("Choco Yellow");
        Pilihan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihan5ActionPerformed(evt);
            }
        });
 
        Pilihan6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Pilihan6.setText("Choco milk");
        Pilihan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihan6ActionPerformed(evt);
            }
        });
 
        Pilihan7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Pilihan7.setText("Dusty White");
        Pilihan7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihan7ActionPerformed(evt);
            }
        });
 
        Pilihan8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Pilihan8.setText("Elegant Blue");
        Pilihan8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihan8ActionPerformed(evt);
            }
        });
 
        Pilihan9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Pilihan9.setText("Global Retro");
        Pilihan9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihan9ActionPerformed(evt);
            }
        });
 
        Pilihan10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Pilihan10.setText("Pink Fanta");
        Pilihan10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihan10ActionPerformed(evt);
            }
        });
 
        Pilihan11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Pilihan11.setText("Silver Saleem");
        Pilihan11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihan11ActionPerformed(evt);
            }
        });
 
        Pilihan12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Pilihan12.setText("Blue Moon");
        Pilihan12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pilihan12ActionPerformed(evt);
            }
        });
 
        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel5.setText("Harga Satuan");
 
        txtSatuan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSatuanActionPerformed(evt);
            }
        });
 
        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel6.setText("Nama Busana");
 
        txtNama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 
        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel7.setText("Jumlah Pembelian");
 
        txtJumlah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 
        btnHitung.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
 
        btnCancel.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
 
        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel9.setText("Diskon");
 
        txtDiskon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel3.setText("Total Bayar");
 
        txtBayar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 
        panel_tempat_gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(panel_tempat_gambar);
 
        jProgressBar1.setBackground(new java.awt.Color(0, 0, 0));
        jProgressBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
 
        jProgressBar2.setBackground(new java.awt.Color(0, 0, 0));
        jProgressBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
 
        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel4.setText("Pembayaran Cash");
 
        txtCash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 
        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jLabel10.setText("Sisa / Kembalian");
 
        txtSisa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
 
        btnBayar.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
 
        jProgressBar4.setBackground(new java.awt.Color(0, 0, 0));
        jProgressBar4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
 
        btnExit.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
 
        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setText("Display Busana");
 
        jProgressBar5.setBackground(new java.awt.Color(0, 0, 0));
        jProgressBar5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
 
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(641, 641, 641)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jProgressBar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnBayar)
                                            .addGap(41, 41, 41)
                                            .addComponent(btnCancel)
                                            .addGap(44, 44, 44)
                                            .addComponent(btnExit))
                                        .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(64, 64, 64))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPilihan)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Pilihan1)
                                                .addGap(30, 30, 30)
                                                .addComponent(Pilihan2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Pilihan3)
                                                    .addComponent(Pilihan5))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Pilihan6)
                                                    .addComponent(Pilihan4)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Pilihan7)
                                                    .addComponent(Pilihan9)
                                                    .addComponent(Pilihan11))
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Pilihan12)
                                                    .addComponent(Pilihan10)
                                                    .addComponent(Pilihan8)))
                                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jNamaPogram, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(20, 20, 20)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(txtSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(18, 18, 18)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(btnHitung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(txtJumlah)))))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel4))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtCash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtSisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jNamaPogram)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPilihan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pilihan1)
                                    .addComponent(Pilihan2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pilihan3)
                                    .addComponent(Pilihan4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pilihan5)
                                    .addComponent(Pilihan6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pilihan7)
                                    .addComponent(Pilihan8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pilihan9)
                                    .addComponent(Pilihan10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pilihan11)
                                    .addComponent(Pilihan12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHitung)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(7, 7, 7)
                                .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtSisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnBayar)
                                    .addComponent(btnExit)
                                    .addComponent(btnCancel)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
 
        pack();
    }// </editor-fold>                        
 
    private void Pilihan1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        //        // TODO add your handling code here:
        txtSatuan.setText("2500000");
        txtNama.setText("Blue Saphire");
        JLabel label_gambar = new JLabel(new ImageIcon("src/gambar/Blue Saphire.png"));
 
        //x,y,lebar, tinggi
        label_gambar.setBounds(2, 2, 2, 2);
        label_gambar.setSize(620, 620);
        panel_tempat_gambar.add(label_gambar);
        panel_tempat_gambar.revalidate();
        panel_tempat_gambar.repaint();
    }                                        
 
    private void Pilihan2ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        txtSatuan.setText("2000000");
        txtNama.setText("Blue Cool");
        JLabel label_gambar1 = new JLabel(new ImageIcon("src/gambar/Blue Cool.png"));
 
        //x,y,lebar, tinggi
        label_gambar1.setBounds(2, 2, 2, 2);
        label_gambar1.setSize(620, 620);
        panel_tempat_gambar.add(label_gambar1);
        panel_tempat_gambar.revalidate();
        panel_tempat_gambar.repaint();
    }                                        
 
    private void Pilihan3ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        txtSatuan.setText("2750000");
        txtNama.setText("Brown Choco");
        JLabel label_gambar3 = new JLabel(new ImageIcon("src/gambar/Brown Choco.png"));
 
        //x,y,lebar, tinggi
        label_gambar3.setBounds(2, 2, 2, 2);
        label_gambar3.setSize(620, 620);
        panel_tempat_gambar.add(label_gambar3);
        panel_tempat_gambar.revalidate();
        panel_tempat_gambar.repaint();
    }                                        
 
    private void Pilihan4ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        txtSatuan.setText("2500000");
        txtNama.setText("Choco Black");
        JLabel label_gambar2 = new JLabel (new ImageIcon("src/gambar/Choco Black.png"));
 
        //x,y,lebar, tinggi
        label_gambar2.setBounds(2, 2, 2, 2);
        label_gambar2.setSize(620, 620);
        panel_tempat_gambar.add(label_gambar2);
        panel_tempat_gambar.revalidate();
        panel_tempat_gambar.repaint();
    }                                        
 
    private void Pilihan5ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        txtSatuan.setText("2250000");
        txtNama.setText("Choco Yellow");
        JLabel label_gambar4 = new JLabel(new ImageIcon("src/gambar/Choco Yellow.png"));
 
        //x,y,lebar, tinggi
        label_gambar4.setBounds(2, 2, 2, 2);
        label_gambar4.setSize(620, 620);
        panel_tempat_gambar.add(label_gambar4);
        panel_tempat_gambar.revalidate();
        panel_tempat_gambar.repaint();
    }                                        
 
    private void Pilihan6ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        txtSatuan.setText("3250000");
        txtNama.setText("Choco milk");
        JLabel label_gambar5 = new JLabel(new ImageIcon("src/gambar/Choco milk.png"));
 
        //x,y,lebar, tinggi
        label_gambar5.setBounds(2, 2, 2, 2);
        label_gambar5.setSize(620, 620);
        panel_tempat_gambar.add(label_gambar5);
        panel_tempat_gambar.revalidate();
        panel_tempat_gambar.repaint();
    }                                        
 
    private void Pilihan7ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        txtSatuan.setText("2500000");
        txtNama.setText("Dusty White");
        JLabel label_gambar6 = new JLabel(new ImageIcon("src/gambar/Dusty White.png"));
 
        //x,y,lebar, tinggi
        label_gambar6.setBounds(1, 1, 1, 1);
        label_gambar6.setSize(620, 620);
        panel_tempat_gambar.add(label_gambar6);
        panel_tempat_gambar.revalidate();
        panel_tempat_gambar.repaint();
    }                                        
 
    private void Pilihan8ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        txtSatuan.setText("2300000");
        txtNama.setText("Elegant Blue");
        JLabel label_gambar7 = new JLabel(new ImageIcon("src/gambar/Elegant Blue.png"));
 
        //x,y,lebar, tinggi
        label_gambar7.setBounds(2, 2, 2, 2);
        label_gambar7.setSize(620, 620);
        panel_tempat_gambar.add(label_gambar7);
        panel_tempat_gambar.revalidate();
        panel_tempat_gambar.repaint();
    }                                        
 
    private void Pilihan9ActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        txtSatuan.setText("2600000");
        txtNama.setText("Global Retro");
        JLabel label_gambar8 = new JLabel(new ImageIcon("src/gambar/Global Retro.png"));
 
        //x,y,lebar, tinggi
        label_gambar8.setBounds(2, 2, 2, 2);
        label_gambar8.setSize(620, 620);
        panel_tempat_gambar.add(label_gambar8);
        panel_tempat_gambar.revalidate();
        panel_tempat_gambar.repaint();
    }                                        
 
    private void Pilihan10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        txtSatuan.setText("2400000");
        txtNama.setText("Pink Fanta");
        JLabel label_gambar9 = new JLabel(new ImageIcon("src/gambar/Pink Fanta.png"));
 
        //x,y,lebar, tinggi
        label_gambar9.setBounds(2, 2, 2, 2);
        label_gambar9.setSize(620, 620);
        panel_tempat_gambar.add(label_gambar9);
        panel_tempat_gambar.revalidate();
        panel_tempat_gambar.repaint();
    }                                        
 
    private void Pilihan11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        txtSatuan.setText("3400000");
        txtNama.setText("Silver Saleem");
        JLabel label_gambar10 = new JLabel(new ImageIcon("src/gambar/Silver Saleem.png"));
 
        //x,y,lebar, tinggi
        label_gambar10.setBounds(2, 2, 2, 2);
        label_gambar10.setSize(620, 620);
        panel_tempat_gambar.add(label_gambar10);
        panel_tempat_gambar.revalidate();
        panel_tempat_gambar.repaint();
    }                                        
 
    private void Pilihan12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        txtSatuan.setText("3000000");
        txtNama.setText("Blue Moon");
        JLabel label_gambar11 = new JLabel(new ImageIcon("src/gambar/Blue Cool.png"));
 
        //x,y,lebar, tinggi
        label_gambar11.setBounds(2, 2, 2, 2);
        label_gambar11.setSize(620, 620);
        panel_tempat_gambar.add(label_gambar11);
        panel_tempat_gambar.revalidate();
        panel_tempat_gambar.repaint();
    }                                        
 
    private void txtSatuanActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                        
 
    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        harga = Integer.parseInt(txtSatuan.getText());
        jumlahBeli = Integer.parseInt(txtJumlah.getText());
        Subtotal = harga * jumlahBeli;
         if(jumlahBeli>=3){
            diskon=Subtotal*0.2;
            }else{
            diskon=0;
            }
         
         txtDiskon.setText(" "+diskon);
       
        totalBayar = Subtotal - diskon;
        txtBayar.setText(" "+totalBayar);  
    }                                        
 
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        txtNama.setText("");
        txtJumlah.setText("");
        txtSatuan.setText("");
        txtBayar.setText("");
        txtDiskon.setText("");
        txtCash.setText("");
        txtSisa.setText("");
        Pilihan1.setSelected(false);
        Pilihan2.setSelected(false);
        Pilihan3.setSelected(false);
        Pilihan4.setSelected(false);
        Pilihan5.setSelected(false);
        Pilihan6.setSelected(false);
        Pilihan7.setSelected(false);
        Pilihan8.setSelected(false);
        Pilihan9.setSelected(false);
        Pilihan10.setSelected(false);
        Pilihan11.setSelected(false);
        Pilihan12.setSelected(false);
        panel_tempat_gambar.removeAll();
    }                                        
 
    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        bayar = Double.parseDouble(txtBayar.getText());
        cash1 = Double.parseDouble(txtCash.getText());
       
        sisa = cash1 - bayar;
        sisa1 =Double.toString(sisa);
                txtSisa.setText("Rp. "+sisa1);
    }                                        
 
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        System.exit(0);
    }                                      
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_penjualan_busana_muslim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_penjualan_busana_muslim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_penjualan_busana_muslim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_penjualan_busana_muslim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_penjualan_busana_muslim().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify                    
    private javax.swing.JRadioButton Pilihan1;
    private javax.swing.JRadioButton Pilihan10;
    private javax.swing.JRadioButton Pilihan11;
    private javax.swing.JRadioButton Pilihan12;
    private javax.swing.JRadioButton Pilihan2;
    private javax.swing.JRadioButton Pilihan3;
    private javax.swing.JRadioButton Pilihan4;
    private javax.swing.JRadioButton Pilihan5;
    private javax.swing.JRadioButton Pilihan6;
    private javax.swing.JRadioButton Pilihan7;
    private javax.swing.JRadioButton Pilihan8;
    private javax.swing.JRadioButton Pilihan9;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHitung;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jNamaPogram;
    private javax.swing.JLabel jPilihan;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane panel_tempat_gambar;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSatuan;
    private javax.swing.JTextField txtSisa;
    // End of variables declaration   
}