/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project1;

/**
 *
 * @author RIAN
 */
public class CobaRES1 extends javax.swing.JFrame {

    /**
     * Creates new form CobaRES1
     */
    public CobaRES1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DnhillHitam16 = new javax.swing.JRadioButton();
        LuckyStrike = new javax.swing.JRadioButton();
        Umild = new javax.swing.JRadioButton();
        Ubold = new javax.swing.JRadioButton();
        LaIce = new javax.swing.JRadioButton();
        MalboroPutih = new javax.swing.JRadioButton();
        MalboroMerah = new javax.swing.JRadioButton();
        Cigarillos = new javax.swing.JRadioButton();
        Djarum76 = new javax.swing.JRadioButton();
        DunhillPutih16 = new javax.swing.JRadioButton();
        Surya16 = new javax.swing.JRadioButton();
        Surya12 = new javax.swing.JRadioButton();
        oleh = new javax.swing.JLabel();
        udin = new javax.swing.JLabel();
        farrel = new javax.swing.JLabel();
        JudulProject = new javax.swing.JLabel();
        Harga1 = new javax.swing.JLabel();
        TampilHargaSatuan1 = new javax.swing.JTextField();
        JumlahBarang = new javax.swing.JLabel();
        TampilJumlahBarang = new javax.swing.JTextField();
        TampilTotalBayar = new javax.swing.JTextField();
        TotalBayar = new javax.swing.JLabel();
        Hitung = new javax.swing.JButton();
        PembayaranCash = new javax.swing.JLabel();
        TambilPembayaranCash = new javax.swing.JTextField();
        KembalianSisa = new javax.swing.JLabel();
        TampilKembalian = new javax.swing.JTextField();
        Bayar = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        fotorokok = new javax.swing.JLabel();
        GarisBatas1 = new javax.swing.JLabel();
        GarisBatas2 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        DnhillHitam16.setBackground(new java.awt.Color(0, 0, 0));
        DnhillHitam16.setForeground(new java.awt.Color(0, 255, 0));
        DnhillHitam16.setText("Dunhill Hitam 16");
        DnhillHitam16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DnhillHitam16ActionPerformed(evt);
            }
        });
        getContentPane().add(DnhillHitam16);
        DnhillHitam16.setBounds(30, 130, 130, 28);

        LuckyStrike.setBackground(new java.awt.Color(0, 0, 0));
        LuckyStrike.setForeground(new java.awt.Color(0, 255, 0));
        LuckyStrike.setText("Lucky Strike");
        LuckyStrike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuckyStrikeActionPerformed(evt);
            }
        });
        getContentPane().add(LuckyStrike);
        LuckyStrike.setBounds(30, 280, 103, 28);

        Umild.setBackground(new java.awt.Color(0, 0, 0));
        Umild.setForeground(new java.awt.Color(0, 255, 0));
        Umild.setText("U Mild");
        Umild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UmildActionPerformed(evt);
            }
        });
        getContentPane().add(Umild);
        Umild.setBounds(160, 280, 70, 28);

        Ubold.setBackground(new java.awt.Color(0, 0, 0));
        Ubold.setForeground(new java.awt.Color(0, 255, 0));
        Ubold.setText("U Bold 12");
        Ubold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UboldActionPerformed(evt);
            }
        });
        getContentPane().add(Ubold);
        Ubold.setBounds(160, 250, 85, 28);

        LaIce.setBackground(new java.awt.Color(0, 0, 0));
        LaIce.setForeground(new java.awt.Color(0, 255, 0));
        LaIce.setText("LA Lights Ice 16");
        LaIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaIceActionPerformed(evt);
            }
        });
        getContentPane().add(LaIce);
        LaIce.setBounds(30, 250, 122, 28);

        MalboroPutih.setBackground(new java.awt.Color(0, 0, 0));
        MalboroPutih.setForeground(new java.awt.Color(0, 255, 0));
        MalboroPutih.setText("Malboro Putih");
        MalboroPutih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalboroPutihActionPerformed(evt);
            }
        });
        getContentPane().add(MalboroPutih);
        MalboroPutih.setBounds(160, 220, 110, 28);

        MalboroMerah.setBackground(new java.awt.Color(0, 0, 0));
        MalboroMerah.setForeground(new java.awt.Color(0, 255, 0));
        MalboroMerah.setText("Malboro Merah");
        MalboroMerah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MalboroMerahActionPerformed(evt);
            }
        });
        getContentPane().add(MalboroMerah);
        MalboroMerah.setBounds(30, 220, 120, 28);

        Cigarillos.setBackground(new java.awt.Color(0, 0, 0));
        Cigarillos.setForeground(new java.awt.Color(0, 255, 0));
        Cigarillos.setText("Cigarillos");
        Cigarillos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CigarillosActionPerformed(evt);
            }
        });
        getContentPane().add(Cigarillos);
        Cigarillos.setBounds(160, 190, 85, 28);

        Djarum76.setBackground(new java.awt.Color(0, 0, 0));
        Djarum76.setForeground(new java.awt.Color(0, 255, 0));
        Djarum76.setText("Djarum 76");
        Djarum76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Djarum76ActionPerformed(evt);
            }
        });
        getContentPane().add(Djarum76);
        Djarum76.setBounds(30, 190, 90, 28);

        DunhillPutih16.setBackground(new java.awt.Color(0, 0, 0));
        DunhillPutih16.setForeground(new java.awt.Color(0, 255, 0));
        DunhillPutih16.setText("Dunhill Putih 16");
        DunhillPutih16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DunhillPutih16ActionPerformed(evt);
            }
        });
        getContentPane().add(DunhillPutih16);
        DunhillPutih16.setBounds(30, 160, 130, 28);

        Surya16.setBackground(new java.awt.Color(0, 0, 0));
        Surya16.setForeground(new java.awt.Color(0, 255, 0));
        Surya16.setText("Surya 16");
        Surya16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Surya16ActionPerformed(evt);
            }
        });
        getContentPane().add(Surya16);
        Surya16.setBounds(160, 160, 82, 28);

        Surya12.setBackground(new java.awt.Color(0, 0, 0));
        Surya12.setForeground(new java.awt.Color(0, 255, 0));
        Surya12.setText("Surya 12");
        Surya12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Surya12ActionPerformed(evt);
            }
        });
        getContentPane().add(Surya12);
        Surya12.setBounds(160, 130, 82, 28);

        oleh.setForeground(new java.awt.Color(0, 255, 255));
        oleh.setText("oleh");
        getContentPane().add(oleh);
        oleh.setBounds(260, 70, 41, 16);

        udin.setForeground(new java.awt.Color(0, 255, 255));
        udin.setText("Arasyi Alimddin");
        getContentPane().add(udin);
        udin.setBounds(290, 70, 88, 16);

        farrel.setForeground(new java.awt.Color(0, 255, 255));
        farrel.setText("Farrel Akbar R");
        getContentPane().add(farrel);
        farrel.setBounds(290, 90, 81, 16);

        JudulProject.setFont(new java.awt.Font("Lucida Calligraphy", 3, 24)); // NOI18N
        JudulProject.setForeground(new java.awt.Color(0, 204, 204));
        JudulProject.setText("Penjualan Rokok");
        getContentPane().add(JudulProject);
        JudulProject.setBounds(210, 20, 240, 40);

        Harga1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Harga1.setForeground(new java.awt.Color(255, 255, 0));
        Harga1.setText("Harga Satuan");
        getContentPane().add(Harga1);
        Harga1.setBounds(40, 340, 110, 20);

        TampilHargaSatuan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilHargaSatuan1ActionPerformed(evt);
            }
        });
        getContentPane().add(TampilHargaSatuan1);
        TampilHargaSatuan1.setBounds(170, 340, 120, 24);

        JumlahBarang.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        JumlahBarang.setForeground(new java.awt.Color(255, 255, 0));
        JumlahBarang.setText("Jumlah Barang");
        getContentPane().add(JumlahBarang);
        JumlahBarang.setBounds(40, 380, 110, 20);

        TampilJumlahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TampilJumlahBarangActionPerformed(evt);
            }
        });
        getContentPane().add(TampilJumlahBarang);
        TampilJumlahBarang.setBounds(170, 380, 120, 24);
        getContentPane().add(TampilTotalBayar);
        TampilTotalBayar.setBounds(170, 450, 120, 24);

        TotalBayar.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        TotalBayar.setForeground(new java.awt.Color(255, 255, 0));
        TotalBayar.setText("Total Bayar");
        getContentPane().add(TotalBayar);
        TotalBayar.setBounds(40, 450, 110, 20);

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        getContentPane().add(Hitung);
        Hitung.setBounds(170, 410, 66, 32);

        PembayaranCash.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        PembayaranCash.setForeground(new java.awt.Color(255, 255, 0));
        PembayaranCash.setText("Pembayaran Cash");
        getContentPane().add(PembayaranCash);
        PembayaranCash.setBounds(40, 480, 140, 20);
        getContentPane().add(TambilPembayaranCash);
        TambilPembayaranCash.setBounds(170, 480, 120, 24);

        KembalianSisa.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        KembalianSisa.setForeground(new java.awt.Color(255, 255, 0));
        KembalianSisa.setText("Kembalian / Sisa");
        getContentPane().add(KembalianSisa);
        KembalianSisa.setBounds(40, 510, 140, 20);
        getContentPane().add(TampilKembalian);
        TampilKembalian.setBounds(170, 510, 120, 24);

        Bayar.setText("Bayar");
        getContentPane().add(Bayar);
        Bayar.setBounds(40, 550, 77, 32);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(240, 550, 51, 32);

        Cancel.setText("Cancel");
        getContentPane().add(Cancel);
        Cancel.setBounds(140, 550, 80, 32);

        fotorokok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/Gambar/rokook.jpg"))); // NOI18N
        fotorokok.setText("Foto");
        fotorokok.setPreferredSize(new java.awt.Dimension(30, 16));
        getContentPane().add(fotorokok);
        fotorokok.setBounds(310, 250, 300, 168);

        GarisBatas1.setText("====================================");
        getContentPane().add(GarisBatas1);
        GarisBatas1.setBounds(40, 310, 260, 16);

        GarisBatas2.setText("====================================");
        getContentPane().add(GarisBatas2);
        GarisBatas2.setBounds(40, 530, 260, 16);

        Background.setBackground(new java.awt.Color(0, 0, 0));
        Background.setFont(new java.awt.Font("Lucida Fax", 3, 24)); // NOI18N
        Background.setForeground(new java.awt.Color(255, 255, 0));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/Gambar/black-background-pattern-3.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 640, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Surya16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Surya16ActionPerformed
        // TODO add your handling code here:
        TampilHargaSatuan1.setText("23000");
    }//GEN-LAST:event_Surya16ActionPerformed

    private void DunhillPutih16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DunhillPutih16ActionPerformed
        // TODO add your handling code here:
        TampilHargaSatuan1.setText("15800");
    }//GEN-LAST:event_DunhillPutih16ActionPerformed

    private void DnhillHitam16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DnhillHitam16ActionPerformed
        // TODO add your handling code here:
        TampilHargaSatuan1.setText("16000");
    }//GEN-LAST:event_DnhillHitam16ActionPerformed

    private void Surya12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Surya12ActionPerformed
        // TODO add your handling code here:
        TampilHargaSatuan1.setText("16500");
    }//GEN-LAST:event_Surya12ActionPerformed

    private void UboldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UboldActionPerformed
        // TODO add your handling code here:
        TampilHargaSatuan1.setText("13000");
    }//GEN-LAST:event_UboldActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void TampilHargaSatuan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilHargaSatuan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TampilHargaSatuan1ActionPerformed

    private void Djarum76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Djarum76ActionPerformed
        // TODO add your handling code here:
        TampilHargaSatuan1.setText("12050");
    }//GEN-LAST:event_Djarum76ActionPerformed

    private void CigarillosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CigarillosActionPerformed
        // TODO add your handling code here:
        TampilHargaSatuan1.setText("10600");
    }//GEN-LAST:event_CigarillosActionPerformed

    private void MalboroMerahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalboroMerahActionPerformed
        // TODO add your handling code here:
        TampilHargaSatuan1.setText("23500");
    }//GEN-LAST:event_MalboroMerahActionPerformed

    private void MalboroPutihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MalboroPutihActionPerformed
        // TODO add your handling code here:
        TampilHargaSatuan1.setText("24000");
    }//GEN-LAST:event_MalboroPutihActionPerformed

    private void LaIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaIceActionPerformed
        // TODO add your handling code here:
        TampilHargaSatuan1.setText("18800");
    }//GEN-LAST:event_LaIceActionPerformed

    private void LuckyStrikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuckyStrikeActionPerformed
        // TODO add your handling code here:
        TampilHargaSatuan1.setText("13000");
    }//GEN-LAST:event_LuckyStrikeActionPerformed

    private void UmildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UmildActionPerformed
        // TODO add your handling code here:
        TampilHargaSatuan1.setText("16300");
    }//GEN-LAST:event_UmildActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        int harga = Integer.parseInt(TampilHargaSatuan1.getText());
        int jumlahBeli = Integer.parseInt(TampilJumlahBarang.getText());
        double Subtotal = harga * jumlahBeli;
    }//GEN-LAST:event_HitungActionPerformed

    private void TampilJumlahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TampilJumlahBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TampilJumlahBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CobaRES1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CobaRES1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CobaRES1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CobaRES1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CobaRES1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Bayar;
    private javax.swing.JButton Cancel;
    private javax.swing.JRadioButton Cigarillos;
    private javax.swing.JRadioButton Djarum76;
    private javax.swing.JRadioButton DnhillHitam16;
    private javax.swing.JRadioButton DunhillPutih16;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel GarisBatas1;
    private javax.swing.JLabel GarisBatas2;
    private javax.swing.JLabel Harga1;
    private javax.swing.JButton Hitung;
    private javax.swing.JLabel JudulProject;
    private javax.swing.JLabel JumlahBarang;
    private javax.swing.JLabel KembalianSisa;
    private javax.swing.JRadioButton LaIce;
    private javax.swing.JRadioButton LuckyStrike;
    private javax.swing.JRadioButton MalboroMerah;
    private javax.swing.JRadioButton MalboroPutih;
    private javax.swing.JLabel PembayaranCash;
    private javax.swing.JRadioButton Surya12;
    private javax.swing.JRadioButton Surya16;
    private javax.swing.JTextField TambilPembayaranCash;
    private javax.swing.JTextField TampilHargaSatuan1;
    private javax.swing.JTextField TampilJumlahBarang;
    private javax.swing.JTextField TampilKembalian;
    private javax.swing.JTextField TampilTotalBayar;
    private javax.swing.JLabel TotalBayar;
    private javax.swing.JRadioButton Ubold;
    private javax.swing.JRadioButton Umild;
    private javax.swing.JLabel farrel;
    private javax.swing.JLabel fotorokok;
    private javax.swing.JLabel oleh;
    private javax.swing.JLabel udin;
    // End of variables declaration//GEN-END:variables
}
